version: "3.9"

services:
  redis:
    image: redis
    restart: always

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "15432:5432"

  phone_checker:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python app/manage.py migrate &&
             python app/manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CELERY_BROKER_URL=redis://redis:6379
      - UPDATE_REGISTRY_ON_START=${UPDATE_REGISTRY_ON_START}

  celery-beat:
    restart: always
    build:
      context: .
    command: ["celery", "--workdir=./app", "-A", "app", "beat", "-l", "info"]
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

  celery-worker:
    restart: always
    build:
      context: .
    command: ["celery", "--workdir=./app", "-A", "app", "worker", "-l", "info"]
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - CELERY_BROKER_URL=redis://redis:6379
      - REGISTRY_URL=${REGISTRY_URL}
