# Generated by Django 5.0.4 on 2024-05-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NumericRegistry",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("code", models.BigIntegerField(max_length=5, verbose_name="Code")),
                (
                    "diapasone_from",
                    models.BigIntegerField(max_length=7, verbose_name="Diapasone From"),
                ),
                (
                    "diapasone_to",
                    models.BigIntegerField(max_length=7, verbose_name="Diapasone To"),
                ),
                (
                    "capasity",
                    models.BigIntegerField(max_length=10, verbose_name="Capasity"),
                ),
                ("operator", models.CharField(max_length=500)),
                ("region", models.CharField(max_length=1000)),
                ("address", models.CharField(max_length=1000)),
                ("inn", models.CharField(max_length=10, verbose_name="INN")),
            ],
            options={
                "db_table": "numeric_registry",
            },
        ),
    ]
