# Generated by Django 5.0.4 on 2024-05-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phone_checker", "0002_alter_numericregistry_capasity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="numericregistry",
            name="inn",
            field=models.CharField(max_length=200, verbose_name="INN"),
        ),
    ]
