# Generated by Django 5.0.4 on 2024-05-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_checker', '0003_alter_numericregistry_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericregistry',
            name='address',
            field=models.CharField(max_length=4000),
        ),
    ]
